server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:4200
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: insurance
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
